name: Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.php'
      - '.github/workflows/release.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: wp-fuse/workflows/.github/workflows/release.yml@main
    secrets: inherit